# 서버 설정
server:
  port: 8089
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
# View Resolver
spring:
  mvc:
    view:
      prefix: /WEB-INF/blog/
      suffix: .jsp
      
# Data Source 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 
    
# JPA 설정
  jpa:
    open-in-view: true  # DB 열결 유지
    database-platform: org.hibernate.dialect.H2Dialect  # H2 데이터베이스에 최적화된 sql 생성
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 엔티티의 변수 이름과 테이블의 컬럼 이름을 동일하게 유지
      ddl-auto: update
      #use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true